name: crossfit_dropin_challenge
description: A CrossFit Drop-in Challenge app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.3.0
  google_sign_in: ^5.4.0
  kakao_flutter_sdk: ^1.4.1
  flutter_naver_login: ^1.8.0
  google_maps_flutter: ^2.2.3
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

