name: crossfit_dropin_challenge
description: A CrossFit Drop-in Challenge app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^5.4.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

